outlier.filter <- c( "Time",                                           
                     "Solder.temp..SU1...C.",                          
                     "Power.value.SU1....",                            
                     "Residual.oxygen..ppm.",                          
                     "N2.valve..1.10...",                              
                     "N2.pressure..mbar.",                             
                     "Wave.1.number.of.revolutions....",               
                     "Wave.1.motor.number.of.revolutions..RPM.",       
                     "Wave.2.number.of.revolutions....",               
                     "Wave.2.motor.number.of.revolutions..RPM.",       
                     "Solderpot.PH.bottom...C.",                       
                     "Solderpot.PH.bottom....",                        
                     "Solderpot.PH.bottom.pyro..offset...C.or...",     
                     "Preheating.bottom.1_1...C.",                     
                     "Preheating.bottom.1_1....",                      
                     "Preheating.bottom.1_1.pyro..offset...C.or...",   
                     "Preheating.bottom.1_2...C.",                     
                     "Preheating.bottom.1_2....",                      
                     "Preheating.bottom.1_2.pyro..offset...C.or...",   
                     "Preheating.bottom.2_1...C.",                     
                     "Preheating.bottom.2_1....",                      
                     "Preheating.bottom.2_1.pyro..offset...C.or...",   
                     "Preheating.bottom.3_1...C.",                     
                     "Preheating.bottom.3_1....",                      
                     "Preheating.bottom.3_1.conv....",                 
                     "Preheating.bottom.3_1.pyro..offset...C.or...",   
                     "Preheating.top.3...C.",                          
                     "Preheating.top.3....",                           
                     "Preheating.top.3.conv....",                      
                     "Preheating.top.3.pyro..offset...C.or...",        
                     "Process.gas.purification..1.ON.",                
                     "Speed.preheating.conveyor..cm.min.",             
                     "Speed.soldering.conveyor..cm.min.",              
                     "Speed.outfeed.conveyor..cm.min.",                
                     "Conveyor.width..mm.",                            
                     "Flux.head.1.active",                             
                     "Fluxer.1.head.1....",                          
                     "Fluxer.flow.rate.sensor.1.board..ml.",           
                     "Fluxer.1.flux.head.1.number.spray.moves.per.PCB",
                     "Boards.in.machine",                              
                     "Electrical.cabinet.temperature...C.",            
                     "Solder.level.minimum.OK",                        
                     "Solder.level.maximum.OK",                        
                     "Solder.level.test.process",                      
                     "Solder.feeder.on",                               
                     "Interface.ready",                                
                     "Ready.on.LVA",                                   
                     "Number.board.in.buffer.before.LGA",              
                     "Automatic.mode.active",                          
                     "Operation.mode",                                 
                     "Conveyor.empty",                                 
                     "Process.infeed",                                 
                     "Separation.active",                              
                     "Timeout.Ersasoft..s.",                           
                     "Average.timeout.Ersasoft..s.",                   
                     "Message.is.available",                           
                     "Message.of.type.Danger.is.available",            
                     "Message.of.type.Failure.is.available",           
                     "Message.of.type.Warning.is.available",           
                     "Message.of.type.Service.is.available",           
                     "Message.of.type.Cyclic.is.available",            
                     "Message.of.type.Waiting.is.available",           
                     "Message.of.type.Info.is.available",              
                     "Periphery..1.ON.",                               
                     "X"   )


draw.filter <- c("Time",                                           
                 #"Solder.temp..SU1...C.",                          
                 "Power.value.SU1....",                            
                 "Residual.oxygen..ppm.",                          
                 #"N2.valve..1.10...",                              
                 "N2.pressure..mbar.",                             
                 "Wave.1.number.of.revolutions....",               
                 #"Wave.1.motor.number.of.revolutions..RPM.",       
                 #"Wave.2.number.of.revolutions....",               
                 #"Wave.2.motor.number.of.revolutions..RPM.",       
                 "Solderpot.PH.bottom...C.",                       
                 #"Solderpot.PH.bottom....",                        
                 # "Solderpot.PH.bottom.pyro..offset...C.or...",     
                 "Preheating.bottom.1_1...C.",                     
                 # "Preheating.bottom.1_1....",                      
                 # "Preheating.bottom.1_1.pyro..offset...C.or...",   
                 # "Preheating.bottom.1_2...C.",                     
                 # "Preheating.bottom.1_2....",                      
                 # "Preheating.bottom.1_2.pyro..offset...C.or...",   
                 "Preheating.bottom.2_1...C.",                     
                 # "Preheating.bottom.2_1....",                      
                 # "Preheating.bottom.2_1.pyro..offset...C.or...",   
                 "Preheating.bottom.3_1...C.",                     
                 # "Preheating.bottom.3_1....",                      
                 # "Preheating.bottom.3_1.conv....",                 
                 # "Preheating.bottom.3_1.pyro..offset...C.or...",   
                 # "Preheating.top.3...C.",                          
                 # "Preheating.top.3....",                           
                 # "Preheating.top.3.conv....",                      
                 # "Preheating.top.3.pyro..offset...C.or...",        
                 # "Process.gas.purification..1.ON.",                
                 # "Speed.preheating.conveyor..cm.min.",             
                 # "Speed.soldering.conveyor..cm.min.",              
                 # "Speed.outfeed.conveyor..cm.min.",                
                 # "Conveyor.width..mm.",                            
                 # "Flux.head.1.active",                             
                 # "Fluxer.1.head.1....",                          
                 "Fluxer.flow.rate.sensor.1.board..ml.",           
                 # "Fluxer.1.flux.head.1.number.spray.moves.per.PCB",
                 # "Boards.in.machine",                              
                 # "Electrical.cabinet.temperature...C.",            
                 # "Solder.level.minimum.OK",                        
                 # "Solder.level.maximum.OK",                        
                 # "Solder.level.test.process",                      
                 # "Solder.feeder.on",                               
                 # "Interface.ready",                                
                 # "Ready.on.LVA",                                   
                 # "Number.board.in.buffer.before.LGA",              
                 # "Automatic.mode.active",                          
                 # "Operation.mode",                                 
                 # "Conveyor.empty",                                 
                 # "Process.infeed",                                 
                 # "Separation.active",                              
                 # "Timeout.Ersasoft..s.",                           
                 # "Average.timeout.Ersasoft..s.",                   
                 # "Message.is.available",                           
                 # "Message.of.type.Danger.is.available",            
                 "Message.of.type.Failure.is.available",           
                 "Message.of.type.Warning.is.available",           
                 # "Message.of.type.Service.is.available",           
                 # "Message.of.type.Cyclic.is.available",            
                 # "Message.of.type.Waiting.is.available",           
                 # "Message.of.type.Info.is.available",              
                 # "Periphery..1.ON.",                               
                 # "X",
                 "outlier")